### ISSUE TITLE
Error: Undefined variable: "$aqua"

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-ui#10] opened 2018-09-11 17:11 UTC
**Describe the bug**
Installation and setup lands me with this in the console:
```
Error: Undefined variable: "$aqua".
```

**To Reproduce**
1. Follow instructions
2. Run the consumer app.

**Expected behavior**

**Comment by allthesignals** [comment] 2018-09-11 17:16
Importing the settings does not fix the issue.

**Comment by allthesignals** [comment] 2018-09-11 19:31
@andycochran Yeah, I deleted it and had the same issue.

**Comment by andycochran** [comment] 2018-10-26 16:34
Closing this, as I cannot reproduce. I assume that `labs-ui/variables` was not imported properly in the consuming app, as `$aqua` is its first defined var.

**Closed by andycochran** 2018-10-26 16:34 UTC
Labels: bug
